# Configure this Discovery Server
eureka:
  instance:
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
    # hostname: localhost
    preferIpAddress: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

  server:
    enable-self-preservation: false
    #eviction-interval-timer-in-ms: 300

spring:
  application:
    name: eureka

server:
  port: 1111
# HTTP (Tomcat) port

#<2>
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
spring.boot.admin.turbine:
  clusters: default
  location: turbine  #<1>
# end::configuration-ui-turbine[]
